# Generated by Django 4.0.3 on 2022-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_fio_citizen_full_name_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.SlugField(unique=True, verbose_name='название'),
        ),
    ]
